version: "3"
services:
  db:
    image: mongo
    ports:
      - '27017:27017'

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "15672:15672"

  scraper:
    build: ./scraper
    depends_on:
      - db
      - rabbitmq

  api:
    build: ./api
    ports:
      - '5000:5000'
    depends_on:
      - db
      - scraper
      - rabbitmq

  async_api:
    build: ./async_api
    ports:
      - '5001:5000'
    depends_on:
      - db
