version: "3"
services:
  db:
    image: mongo
    ports:
      - '27017:27017'

  scraper:
    build: ./scraper
    depends_on:
      - db

  api:
    build: ./api
    ports:
      - '5000:5000'
    depends_on:
      - db
      - scraper
